camel.main.run-controller=true

# Kafka bootstrap address used by the routes
camel.component.kafka.brokers=localhost:9092
camel.component.kafka.request-required-acks=all
camel.component.kafka.enable-idempotence=true
camel.component.kafka.auto-commit-enable=false
camel.component.kafka.allow-manual-commit=true

management.endpoints.web.exposure.include=health,info,metrics
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
