camel.main.run-controller=true

# Kafka bootstrap address used by the routes
camel.component.kafka.brokers=localhost:9092

management.endpoints.web.exposure.include=health,info,metrics
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
