spring.application.name=concurrent-kafka-consumer

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.client-id=concurrent-kafka
spring.kafka.consumer.group-id=concurrent-kafka-consumer
spring.kafka.listener.change-consumer-thread-name=true
spring.kafka.listener.concurrency=3
spring.threads.virtual.enabled=true

management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.endpoints.web.exposure.include=health,info,metrics
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
