name: analytics-spring-cloud-streams-kafka-consumer

on:
  push:
    paths:
      - "kafka-streams/analytics-spring-cloud-streams-kafka-consumer/**"
    branches: [ main ]
  pull_request:
    paths:
      - "kafka-streams/analytics-spring-cloud-streams-kafka-consumer/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "kafka-streams/analytics-spring-cloud-streams-kafka-consumer"
    steps:
    - uses: actions/checkout@v5
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v5.0.0
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw -B clean verify --file pom.xml
