name: kafka-spring-modulith-outbox-pattern-sample

on:
  push:
    paths:
      - "spring-modulith-outbox-pattern/**"
    branches: [ main ]
  pull_request:
    paths:
      - "spring-modulith-outbox-pattern/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "spring-modulith-outbox-pattern"
    strategy:
      matrix:
        java: ["25"]
    steps:
    - uses: actions/checkout@v5
      with:
          fetch-depth: 0
    - uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'graalvm'
        java-version: ${{ matrix.java }}
        cache: "maven"
  
    - name: Printing versions
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml

    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Build and Publish Docker Image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        ./mvnw -Pnative spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/spring-modulith-outbox-pattern
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-modulith-outbox-pattern
