name: quarkus-kafka-demo-sample

on:
  push:
    paths:
      - "quarkus-kafka-demo/**"
    branches: [ main ]
  pull_request:
    paths:
      - "quarkus-kafka-demo/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "quarkus-kafka-demo"
    strategy:
      matrix:
        java: ["25"]
    steps:
    - uses: actions/checkout@v5
      with:
          fetch-depth: 0
    - uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'graalvm'
        java-version: ${{ matrix.java }}
        cache: "maven"
  
    - name: Printing versions
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml
